/**
 * Carrier rate cards, for postage the 3PL does not bill (#34).
 *
 * DHL BPM Ground labels are generated by the 3PL against Rad & Happy's own DHL
 * eCommerce account, so they export at $0.00 and appear on no Evobox invoice.
 * That is 1,726 of 2,508 shipments over thirteen months — 69% of the shipment
 * base with no cost attached anywhere.
 *
 * The rate card closes that. Weight and destination postcode are already on
 * every shipment row, so postage is **computed per shipment**, not averaged
 * across them. That matters here: BPM parcels run from 0.06 to 8.15 lb and
 * reach every zone, and a single average over that spread would be wrong in
 * both directions at once.
 *
 * ## The rates are higher than they look
 *
 * A 2.5 lb parcel costs $7.08 to zone 1 and $10.74 to zone 8, before fuel.
 * An earlier estimate of ~$2.50-4.00 for "cheap book rate" was wrong by a
 * factor of three, which is exactly what the 3PL said when asked.
 */

export interface RateCard {
  carrier: string;
  service: string;
  effectiveFrom: string;
  /** Zones this card prices, in the order the rate arrays use. */
  zones: number[];
  /**
   * Ascending weight breaks. A parcel is charged at the first break greater
   * than or equal to its weight — carriers round up, never down or to nearest.
   */
  breaks: {
    weightLb: number;
    /** Added to the zone rate. A flat amount per break, not a percentage. */
    fuelSurchargeCents: number;
    /** Rate per zone, indexed the same as `zones`. */
    zoneRatesCents: number[];
  }[];
}

/** DHL BPM Ground, Rad & Happy client rates, 2026. Fuel surcharge October 2026. */
export const DHL_BPM_GROUND_2026: RateCard = {
  carrier: "dhl_ecommerce",
  service: "DHL BPM Ground",
  effectiveFrom: "2026-01-01",
  zones: [1, 2, 3, 4, 5, 6, 7, 8],
  breaks: [
    { weightLb: 1, fuelSurchargeCents: 30, zoneRatesCents: [498, 498, 505, 514, 534, 556, 583, 665] },
    { weightLb: 1.5, fuelSurchargeCents: 45, zoneRatesCents: [565, 565, 573, 588, 615, 654, 695, 795] },
    { weightLb: 2, fuelSurchargeCents: 60, zoneRatesCents: [614, 614, 633, 646, 686, 733, 790, 915] },
    { weightLb: 2.5, fuelSurchargeCents: 75, zoneRatesCents: [708, 708, 726, 746, 799, 859, 930, 1074] },
    { weightLb: 3, fuelSurchargeCents: 90, zoneRatesCents: [769, 769, 791, 816, 875, 948, 1033, 1203] },
    { weightLb: 3.5, fuelSurchargeCents: 105, zoneRatesCents: [840, 840, 866, 899, 985, 1065, 1146, 1339] },
    { weightLb: 4, fuelSurchargeCents: 120, zoneRatesCents: [900, 900, 933, 966, 1068, 1163, 1251, 1466] },
    { weightLb: 4.5, fuelSurchargeCents: 135, zoneRatesCents: [974, 974, 1005, 1046, 1160, 1265, 1369, 1601] },
    { weightLb: 5, fuelSurchargeCents: 150, zoneRatesCents: [1034, 1034, 1069, 1115, 1239, 1358, 1473, 1730] },
    { weightLb: 6, fuelSurchargeCents: 180, zoneRatesCents: [1171, 1171, 1214, 1266, 1420, 1560, 1699, 1994] },
    { weightLb: 7, fuelSurchargeCents: 210, zoneRatesCents: [1299, 1299, 1354, 1410, 1593, 1760, 1915, 2256] },
    { weightLb: 8, fuelSurchargeCents: 240, zoneRatesCents: [1439, 1439, 1501, 1570, 1775, 1961, 2144, 2525] },
    { weightLb: 9, fuelSurchargeCents: 270, zoneRatesCents: [1571, 1571, 1641, 1720, 1949, 2160, 2364, 2789] },
    { weightLb: 10, fuelSurchargeCents: 300, zoneRatesCents: [1706, 1706, 1781, 1868, 2120, 2356, 2584, 3051] },
    { weightLb: 11, fuelSurchargeCents: 330, zoneRatesCents: [1838, 1838, 1921, 2016, 2299, 2554, 2804, 3318] },
    { weightLb: 12, fuelSurchargeCents: 360, zoneRatesCents: [1966, 1966, 2060, 2166, 2474, 2754, 3076, 3581] },
    { weightLb: 13, fuelSurchargeCents: 390, zoneRatesCents: [2106, 2106, 2203, 2316, 2650, 2954, 3305, 3844] },
    { weightLb: 14, fuelSurchargeCents: 420, zoneRatesCents: [2238, 2238, 2344, 2466, 2826, 3155, 3530, 4110] },
  ],
};

export type RateOutcome =
  | { ok: true; cents: number; breakWeightLb: number; zone: number }
  | { ok: false; reason: "over_max_weight" | "unknown_zone" | "no_weight" };

/**
 * What one shipment's label costs.
 *
 * Returns a discriminated result rather than a number or null. An unrateable
 * shipment — no weight, a zone off the card, a parcel above the heaviest break
 * — must not collapse into the same value as a cheap one, which is how a
 * missing cost becomes a free shipment.
 */
export function rateShipment(card: RateCard, weightLb: number | null, zone: number | null): RateOutcome {
  if (weightLb === null || !Number.isFinite(weightLb) || weightLb <= 0) {
    return { ok: false, reason: "no_weight" };
  }
  if (zone === null) return { ok: false, reason: "unknown_zone" };

  const zoneIndex = card.zones.indexOf(zone);
  if (zoneIndex === -1) return { ok: false, reason: "unknown_zone" };

  // Carriers charge the first break at or above the actual weight.
  const chargedBreak = card.breaks.find((b) => weightLb <= b.weightLb);
  if (!chargedBreak) return { ok: false, reason: "over_max_weight" };

  return {
    ok: true,
    cents: chargedBreak.zoneRatesCents[zoneIndex] + chargedBreak.fuelSurchargeCents,
    breakWeightLb: chargedBreak.weightLb,
    zone,
  };
}

export interface RateBand {
  ok: true;
  minCents: number;
  maxCents: number;
  cheapestZone: number;
  dearestZone: number;
  breakWeightLb: number;
}

/**
 * The cost range across every zone, for use while the zone chart is unknown.
 *
 * A band is honest in a way a midpoint is not: it states what is actually
 * known. Zone 8 costs roughly a third more than zone 1 at these weights, so a
 * midpoint would be a number nobody can defend and everyone would quote.
 */
export function rateBand(card: RateCard, weightLb: number | null): RateBand | { ok: false; reason: RateOutcome extends { ok: false; reason: infer R } ? R : never } {
  const rated = card.zones
    .map((zone) => ({ zone, outcome: rateShipment(card, weightLb, zone) }))
    .filter((r): r is { zone: number; outcome: Extract<RateOutcome, { ok: true }> } => r.outcome.ok);

  if (rated.length === 0) {
    const probe = rateShipment(card, weightLb, card.zones[0]);
    return { ok: false, reason: probe.ok ? ("unknown_zone" as never) : (probe.reason as never) };
  }

  const cheapest = rated.reduce((a, b) => (b.outcome.cents < a.outcome.cents ? b : a));
  const dearest = rated.reduce((a, b) => (b.outcome.cents > a.outcome.cents ? b : a));
  return {
    ok: true,
    minCents: cheapest.outcome.cents,
    maxCents: dearest.outcome.cents,
    cheapestZone: cheapest.zone,
    dearestZone: dearest.zone,
    breakWeightLb: rated[0].outcome.breakWeightLb,
  };
}
