/**
 * Carrier rate cards, for postage the 3PL does not bill (#34).
 *
 * DHL BPM Ground labels are generated by the 3PL against Rad & Happy's own DHL
 * eCommerce account, so they export at $0.00 and appear on no Evobox invoice.
 * That is 1,726 of 2,508 shipments over thirteen months — 69% of the shipment
 * base with no cost attached anywhere.
 *
 * The rate card closes that. Weight and destination postcode are already on
 * every shipment row, so postage is **computed per shipment**, not averaged
 * across them. That matters here: BPM parcels run from 0.06 to 8.15 lb and
 * reach every zone, and a single average over that spread would be wrong in
 * both directions at once.
 *
 * ## The rates are higher than they look
 *
 * A 2.5 lb parcel costs $7.08 to zone 1 and $10.74 to zone 8, before fuel.
 * An earlier estimate of ~$2.50-4.00 for "cheap book rate" was wrong by a
 * factor of three, which is exactly what the 3PL said when asked.
 */

export interface RateCard {
  carrier: string;
  service: string;
  effectiveFrom: string;
  /** Zones this card prices, in the order the rate arrays use. */
  zones: number[];
  /**
   * Ascending weight breaks. A parcel is charged at the first break greater
   * than or equal to its weight — carriers round up, never down or to nearest.
   */
  breaks: {
    weightLb: number;
    /** Added to the zone rate. A flat amount per break, not a percentage. */
    fuelSurchargeCents: number;
    /** Rate per zone, indexed the same as `zones`. */
    zoneRatesCents: number[];
  }[];
}

/** DHL BPM Ground, Rad & Happy client rates, 2026. Fuel surcharge October 2026. */
export const DHL_BPM_GROUND_2026: RateCard = {
  carrier: "dhl_ecommerce",
  service: "DHL BPM Ground",
  effectiveFrom: "2026-01-01",
  zones: [1, 2, 3, 4, 5, 6, 7, 8],
  breaks: [
    { weightLb: 1, fuelSurchargeCents: 30, zoneRatesCents: [498, 498, 505, 514, 534, 556, 583, 665] },
    { weightLb: 1.5, fuelSurchargeCents: 45, zoneRatesCents: [565, 565, 573, 588, 615, 654, 695, 795] },
    { weightLb: 2, fuelSurchargeCents: 60, zoneRatesCents: [614, 614, 633, 646, 686, 733, 790, 915] },
    { weightLb: 2.5, fuelSurchargeCents: 75, zoneRatesCents: [708, 708, 726, 746, 799, 859, 930, 1074] },
    { weightLb: 3, fuelSurchargeCents: 90, zoneRatesCents: [769, 769, 791, 816, 875, 948, 1033, 1203] },
    { weightLb: 3.5, fuelSurchargeCents: 105, zoneRatesCents: [840, 840, 866, 899, 985, 1065, 1146, 1339] },
    { weightLb: 4, fuelSurchargeCents: 120, zoneRatesCents: [900, 900, 933, 966, 1068, 1163, 1251, 1466] },
    { weightLb: 4.5, fuelSurchargeCents: 135, zoneRatesCents: [974, 974, 1005, 1046, 1160, 1265, 1369, 1601] },
    { weightLb: 5, fuelSurchargeCents: 150, zoneRatesCents: [1034, 1034, 1069, 1115, 1239, 1358, 1473, 1730] },
    { weightLb: 6, fuelSurchargeCents: 180, zoneRatesCents: [1171, 1171, 1214, 1266, 1420, 1560, 1699, 1994] },
    { weightLb: 7, fuelSurchargeCents: 210, zoneRatesCents: [1299, 1299, 1354, 1410, 1593, 1760, 1915, 2256] },
    { weightLb: 8, fuelSurchargeCents: 240, zoneRatesCents: [1439, 1439, 1501, 1570, 1775, 1961, 2144, 2525] },
    { weightLb: 9, fuelSurchargeCents: 270, zoneRatesCents: [1571, 1571, 1641, 1720, 1949, 2160, 2364, 2789] },
    { weightLb: 10, fuelSurchargeCents: 300, zoneRatesCents: [1706, 1706, 1781, 1868, 2120, 2356, 2584, 3051] },
    { weightLb: 11, fuelSurchargeCents: 330, zoneRatesCents: [1838, 1838, 1921, 2016, 2299, 2554, 2804, 3318] },
    { weightLb: 12, fuelSurchargeCents: 360, zoneRatesCents: [1966, 1966, 2060, 2166, 2474, 2754, 3076, 3581] },
    { weightLb: 13, fuelSurchargeCents: 390, zoneRatesCents: [2106, 2106, 2203, 2316, 2650, 2954, 3305, 3844] },
    { weightLb: 14, fuelSurchargeCents: 420, zoneRatesCents: [2238, 2238, 2344, 2466, 2826, 3155, 3530, 4110] },
  ],
};

/**
 * USPS Media Mail, client rates 2026.
 *
 * Flat: no zones and no dimensional weight. Media Mail is priced on actual
 * weight alone, which is why switching to it removes both of the inputs that
 * were outstanding from DHL — the zone chart and the DIM divisor — and why it
 * is dramatically cheaper for a large light parcel. A 1.45lb wall calendar
 * rates at the 2lb break, $6.41, against $15.37 billed today.
 *
 * Modelled with a single zone. `rateShipment` treats a one-zone card as
 * zoneless and does not require a zone to be supplied.
 *
 * **Eligibility is a real constraint, not a formality** — see
 * MEDIA_MAIL_ELIGIBILITY_NOTE.
 */
export const USPS_MEDIA_MAIL_2026: RateCard = {
  carrier: "usps",
  service: "USPS Media Mail",
  effectiveFrom: "2026-01-01",
  zones: [1],
  breaks: [
    { weightLb: 1, fuelSurchargeCents: 0, zoneRatesCents: [549] },
    { weightLb: 2, fuelSurchargeCents: 0, zoneRatesCents: [641] },
    { weightLb: 3, fuelSurchargeCents: 0, zoneRatesCents: [733] },
    { weightLb: 4, fuelSurchargeCents: 0, zoneRatesCents: [825] },
    { weightLb: 5, fuelSurchargeCents: 0, zoneRatesCents: [918] },
    { weightLb: 6, fuelSurchargeCents: 0, zoneRatesCents: [1010] },
    { weightLb: 7, fuelSurchargeCents: 0, zoneRatesCents: [1101] },
    { weightLb: 8, fuelSurchargeCents: 0, zoneRatesCents: [1194] },
    { weightLb: 9, fuelSurchargeCents: 0, zoneRatesCents: [1286] },
    { weightLb: 10, fuelSurchargeCents: 0, zoneRatesCents: [1378] },
    { weightLb: 11, fuelSurchargeCents: 0, zoneRatesCents: [1470] },
    { weightLb: 12, fuelSurchargeCents: 0, zoneRatesCents: [1563] },
    { weightLb: 13, fuelSurchargeCents: 0, zoneRatesCents: [1654] },
    { weightLb: 14, fuelSurchargeCents: 0, zoneRatesCents: [1746] },
    { weightLb: 15, fuelSurchargeCents: 0, zoneRatesCents: [1839] },
    { weightLb: 16, fuelSurchargeCents: 0, zoneRatesCents: [1930] },
    { weightLb: 17, fuelSurchargeCents: 0, zoneRatesCents: [2023] },
    { weightLb: 18, fuelSurchargeCents: 0, zoneRatesCents: [2115] },
    { weightLb: 19, fuelSurchargeCents: 0, zoneRatesCents: [2206] },
    { weightLb: 20, fuelSurchargeCents: 0, zoneRatesCents: [2299] },
    { weightLb: 21, fuelSurchargeCents: 0, zoneRatesCents: [2391] },
    { weightLb: 22, fuelSurchargeCents: 0, zoneRatesCents: [2483] },
    { weightLb: 23, fuelSurchargeCents: 0, zoneRatesCents: [2575] },
    { weightLb: 24, fuelSurchargeCents: 0, zoneRatesCents: [2668] },
    { weightLb: 25, fuelSurchargeCents: 0, zoneRatesCents: [2759] },
    { weightLb: 26, fuelSurchargeCents: 0, zoneRatesCents: [2851] },
    { weightLb: 27, fuelSurchargeCents: 0, zoneRatesCents: [2944] },
    { weightLb: 28, fuelSurchargeCents: 0, zoneRatesCents: [3036] },
    { weightLb: 29, fuelSurchargeCents: 0, zoneRatesCents: [3128] },
    { weightLb: 30, fuelSurchargeCents: 0, zoneRatesCents: [3220] },
  ],
};

/**
 * Media Mail is restricted content, and the restriction is enforced.
 *
 * USPS limits it to books of at least 8 printed pages, printed music, sound
 * recordings, play scripts, printed educational reference charts and similar
 * *reading matter*. Items with blank pages to write in, and calendars, are the
 * usual disputed cases — a dated planner is largely blank by design, and a
 * wall calendar is not reading matter.
 *
 * USPS may inspect Media Mail, and the remedy is postage due at the Ground
 * Advantage rate or refusal, assessed against the sender. At 1,726 parcels a
 * year that is not a rounding error, so eligibility is worth confirming in
 * writing with the 3PL before the saving is treated as banked. This note is
 * here because the rate card alone makes the switch look purely like a win.
 */
export const MEDIA_MAIL_ELIGIBILITY_NOTE =
  "USPS Media Mail is limited to books and similar reading matter. Planners with " +
  "blank pages and wall calendars are commonly held ineligible; USPS may inspect " +
  "and assess postage due at the Ground Advantage rate. Confirm eligibility per " +
  "product before relying on these rates.";

export type RateOutcome =
  | { ok: true; cents: number; breakWeightLb: number; zone: number }
  | { ok: false; reason: "over_max_weight" | "unknown_zone" | "no_weight" };

/**
 * What one shipment's label costs.
 *
 * Returns a discriminated result rather than a number or null. An unrateable
 * shipment — no weight, a zone off the card, a parcel above the heaviest break
 * — must not collapse into the same value as a cheap one, which is how a
 * missing cost becomes a free shipment.
 */
export function rateShipment(card: RateCard, weightLb: number | null, zone: number | null): RateOutcome {
  if (weightLb === null || !Number.isFinite(weightLb) || weightLb <= 0) {
    return { ok: false, reason: "no_weight" };
  }
  // A single-zone card is zoneless — USPS Media Mail is priced on weight
  // alone — so there is no zone for the caller to be missing.
  const effectiveZone = zone === null && card.zones.length === 1 ? card.zones[0] : zone;
  if (effectiveZone === null) return { ok: false, reason: "unknown_zone" };

  const zoneIndex = card.zones.indexOf(effectiveZone);
  if (zoneIndex === -1) return { ok: false, reason: "unknown_zone" };

  // Carriers charge the first break at or above the actual weight.
  const chargedBreak = card.breaks.find((b) => weightLb <= b.weightLb);
  if (!chargedBreak) return { ok: false, reason: "over_max_weight" };

  return {
    ok: true,
    cents: chargedBreak.zoneRatesCents[zoneIndex] + chargedBreak.fuelSurchargeCents,
    breakWeightLb: chargedBreak.weightLb,
    zone: effectiveZone,
  };
}

export interface RateBand {
  ok: true;
  minCents: number;
  maxCents: number;
  cheapestZone: number;
  dearestZone: number;
  breakWeightLb: number;
}

/**
 * The cost range across every zone, for use while the zone chart is unknown.
 *
 * A band is honest in a way a midpoint is not: it states what is actually
 * known. Zone 8 costs roughly a third more than zone 1 at these weights, so a
 * midpoint would be a number nobody can defend and everyone would quote.
 */
export function rateBand(card: RateCard, weightLb: number | null): RateBand | { ok: false; reason: RateOutcome extends { ok: false; reason: infer R } ? R : never } {
  const rated = card.zones
    .map((zone) => ({ zone, outcome: rateShipment(card, weightLb, zone) }))
    .filter((r): r is { zone: number; outcome: Extract<RateOutcome, { ok: true }> } => r.outcome.ok);

  if (rated.length === 0) {
    const probe = rateShipment(card, weightLb, card.zones[0]);
    return { ok: false, reason: probe.ok ? ("unknown_zone" as never) : (probe.reason as never) };
  }

  const cheapest = rated.reduce((a, b) => (b.outcome.cents < a.outcome.cents ? b : a));
  const dearest = rated.reduce((a, b) => (b.outcome.cents > a.outcome.cents ? b : a));
  return {
    ok: true,
    minCents: cheapest.outcome.cents,
    maxCents: dearest.outcome.cents,
    cheapestZone: cheapest.zone,
    dearestZone: dearest.zone,
    breakWeightLb: rated[0].outcome.breakWeightLb,
  };
}

/**
 * Dimensional weight — what a carrier bills a large, light parcel on.
 *
 * `divisor` is required and has no default on purpose. It is carrier- and
 * contract-specific (commonly 139, 166 or 194 for domestic ground), and the
 * difference between 139 and 194 is 40% of the billed weight. Guessing it
 * would produce a confident number that nobody could check, which is worse
 * here than having no number.
 *
 * The carrier charges the greater of actual and dimensional weight, which is
 * what `billableWeightLb` returns.
 */
export function dimensionalWeightLb(
  lengthIn: number | null,
  widthIn: number | null,
  heightIn: number | null,
  divisor: number,
): number | null {
  if (lengthIn === null || widthIn === null || heightIn === null) return null;
  if (!(lengthIn > 0 && widthIn > 0 && heightIn > 0) || !(divisor > 0)) return null;
  return (lengthIn * widthIn * heightIn) / divisor;
}

export type BillableWeight =
  | { ok: true; weightLb: number; basis: "actual" | "dimensional" }
  | { ok: false; reason: "no_weight" | "no_dimensions" };

/**
 * The weight a parcel is actually rated on.
 *
 * Returns which basis won, because "this calendar is billed as 4.3lb though it
 * weighs 1.3lb" is the fact that explains the bill, and a bare number hides it.
 */
export function billableWeightLb(
  actualLb: number | null,
  dims: { lengthIn: number | null; widthIn: number | null; heightIn: number | null },
  divisor: number,
): BillableWeight {
  const dim = dimensionalWeightLb(dims.lengthIn, dims.widthIn, dims.heightIn, divisor);
  if (actualLb === null || !(actualLb > 0)) {
    return dim === null ? { ok: false, reason: "no_weight" } : { ok: true, weightLb: dim, basis: "dimensional" };
  }
  if (dim === null) return { ok: true, weightLb: actualLb, basis: "actual" };
  return dim > actualLb
    ? { ok: true, weightLb: dim, basis: "dimensional" }
    : { ok: true, weightLb: actualLb, basis: "actual" };
}

export type PostageBasis = "billed" | "derived" | "unknown";

export interface PostageEstimate {
  cents: number | null;
  basis: PostageBasis;
  /** The weight the rate came from, when derived. */
  ratedWeightLb: number | null;
  note?: string;
}

/**
 * Postage for a parcel, billed where known and derived where not.
 *
 * 69% of shipments bill to a carrier account the 3PL does not invoice, so
 * postage has been a floor. Media Mail changes what is possible: no zones, no
 * dimensional weight, a published rate card — so a parcel's postage is a pure
 * function of its weight and can be computed rather than waited for.
 *
 * `basis` is the point. A derived figure is an estimate from a rate card, not
 * a number anyone was charged, and the two must never sum into one total that
 * reads as billed. A caller that wants only real money filters on `billed`;
 * one that wants a best estimate takes both and says which is which.
 *
 * Deriving is only honest because Media Mail is flat. It would be wrong for
 * DHL BPM, where the zone is unknown and the answer is a range.
 */
export function estimatePostage(
  billedCents: number | null,
  weightLb: number | null,
  card: RateCard = USPS_MEDIA_MAIL_2026,
): PostageEstimate {
  if (billedCents !== null) {
    return { cents: billedCents, basis: "billed", ratedWeightLb: null };
  }

  const rated = rateShipment(card, weightLb, null);
  if (rated.ok) {
    return {
      cents: rated.cents,
      basis: "derived",
      ratedWeightLb: rated.breakWeightLb,
      note: `Not billed to us. Computed from ${card.service} at the ${rated.breakWeightLb}lb break — an estimate, not a charge.`,
    };
  }

  return {
    cents: null,
    basis: "unknown",
    ratedWeightLb: null,
    note:
      rated.reason === "no_weight"
        ? "Not billed to us and no weight recorded, so nothing can be derived."
        : `Not billed to us and ${card.service} cannot price it (${rated.reason}).`,
  };
}

export interface PostageRollup {
  shipments: number;
  billedCents: number;
  derivedCents: number;
  unknown: number;
  /** Share of shipments whose postage is a real charge rather than an estimate. */
  billedShare: number;
}

/**
 * Totals postage while keeping billed and derived apart.
 *
 * Returned as separate figures rather than one sum, because a total that mixes
 * them is indistinguishable from a total anyone was charged — which is the
 * whole reason postage coverage is reported in the first place.
 */
export function rollUpPostage(estimates: PostageEstimate[]): PostageRollup {
  const billed = estimates.filter((e) => e.basis === "billed");
  const derived = estimates.filter((e) => e.basis === "derived");
  return {
    shipments: estimates.length,
    billedCents: billed.reduce((s, e) => s + (e.cents ?? 0), 0),
    derivedCents: derived.reduce((s, e) => s + (e.cents ?? 0), 0),
    unknown: estimates.filter((e) => e.basis === "unknown").length,
    billedShare: estimates.length === 0 ? 0 : Number((billed.length / estimates.length).toFixed(4)),
  };
}
